rootProject.name = "mixinextras"
include("platform")
include("platform:ap")
include("platform:common")
include("platform:fabric")
include("platform:forge")
include("platform:neoforge")
include("mixin-versions")
include("mixin-versions:v0_8")
include("mixin-versions:v0_8_3")
include("mixin-versions:v0_8_4")
